### PR TITLE
fix(redis): prevent invalid use of keepTtl with expiration options

### LINKED ISSUE #104: Add validation on set keepTtl properties
You can use this option to set a key without affecting the ttl already define: 
```yaml 
options: 
  keepTtl: true 
```

You can use this options to set a ttl on key:
```yaml
options: 
  expirationDuration: PT10S 
```

But specifying both are invalid for redis, since redis will never be able to know if we need to keep the tll or set a new one: 
```yaml
options: 
  keepTtl: true 
  expirationDuration: PT10S 
```

We need to add a validation rules to prevent using `keepTtl` with an expiration

### PR DESCRIPTION
**Pull request by Malaydewangan09**
Added validation to disallow combining `keepTtl` with `expirationDuration` or `expirationDate`.
fixes #104

### CODE REVIEW

File: src/main/java/io/kestra/plugin/redis/string/Set.java [hunk 1]
```diff
@@ -11,6 +11,7 @@
 import io.kestra.plugin.redis.models.SerdeType;
 import io.lettuce.core.SetArgs;
 import io.swagger.v3.oas.annotations.media.Schema;
+import jakarta.validation.constraints.AssertTrue;
```
Comment (fdelbrayelle) [inline src/main/java/io/kestra/plugin/redis/string/Set.java:14]: Unused import to remove

**Review by fdelbrayelle — APPROVED** [review]
