### PR TITLE
fix(ListPush): String as list

### LINKED ISSUE #26: Cannot pass a list to the ListPush task from inputs or previous task
### Expected Behavior

it might be that I'm doing something wrong here, but I want to store a list of strings in Redis for a given key. 

When I do it this way, everything works fine:

```yaml
id: redisKV
namespace: dev

tasks:
  - id: pushListPlugins
    type: io.kestra.plugin.redis.ListPush
    url: redis://host.docker.internal:6379/0
    key: favoritePlugins
    from:
      - redis
      - dbt
      - duckdb
```

image

But passing it from other task or inputs doesn't work - I don't know how to convert that string to an actual list for the ListPush task: 

```yaml
id: cannotExpandTheList
namespace: dev

inputs:
  - name: values
    type: JSON
    defaults: |
      [
        {"dbt": ["build", "test", "snapshot"]},
        {"aws": ["s3", "sqs", "sns", "athena"]},
        {"gcp": ["big-query", "gcs", "cloudrun"]}
      ]

tasks:
  - id: foreach
    type: io.kestra.core.tasks.flows.EachParallel
    value: "{{inputs.values}}"
    tasks:
      - id: pushListPlugins
        type: io.kestra.plugin.redis.ListPush
        url: redis://host.docker.internal:6379/0
        serdeType: JSON
        key: "{{json(taskrun.value) | keys | first}}"
        from: "{{ taskrun.value | jq('.[]') | first }}"
```

error: `Illegal character in path at index 0: ["s3","sqs","sns","athena"]`

### Actual Behaviour

_No response_

### Steps To Reproduce

_No response_

### Environment Information

- Kestra Version: develop full image

### Example flow

_No response_

### PR DESCRIPTION
**Pull request by Skraye**
Allow passing list in String format

close #26

### CODE REVIEW

File: src/main/java/io/kestra/plugin/redis/ListPush.java [hunk 1]
```diff
@@ -68,16 +68,30 @@ public Output run(RunContext runContext) throws Exception {
...
             Integer count;
-            if (this.from instanceof String fromUrl) {
-                URI from = new URI(runContext.render(fromUrl));
-                try (BufferedReader inputStream = new BufferedReader(new InputStreamReader(runContext.uriToInputStream(from)))) {
+
+            Object from = null;
+            if (this.from instanceof String fromString) {
+                String renderedFrom = runContext.render(fromString);
+                try {
+                    ObjectMapper mapper = new ObjectMapper();
```
Comment (loicmathieu) [inline src/main/java/io/kestra/plugin/redis/ListPush.java:76]: You should retrieve an instance of an Object Mapper as a constant using our Jackson helper to have a pre-configured mapper.

**Review by loicmathieu — CHANGES_REQUESTED** [review]

**Review by loicmathieu — APPROVED** [review]
LGTM
